name: xr-trunk

on:
  push:
    braches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

  Build-Android:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls -la
