name: xr-trunk

on:
  push:
    braches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm run test -- --coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODE_COV_TOKEN }} #required
          file: ./coverage/coverage-final.json #optional
          flags: unittests #optional
          name: codecov-umbrella #optional
          fail_ci_if_error: true #optional (default = false)

  Build-Android:
    needs: [Build]
    runs-on: ubuntu-latest
    container:
      image: 'docker://reactnativecommunity/react-native-android'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build Apk
        run: cd android && ./gradlew assembleDebug
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Android
          path: ./android/app/build/outputs
  Build-iOS:
    needs: [Build]
    runs-on: macos-latest
    steps:
      - name: Setup (Bundler)
        run: |
          if which ruby >/dev/null && which gem >/dev/null; then
            GEM_HOME=$(ruby -r rubygems -e 'puts Gem.user_dir')/bin
            echo "::add-path::$GEM_HOME"
          fi
          gem install bundler --user-install

      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

      - name: Setup (Fastlane)
        run: |
          cd ios 
          bundle install
