name: xr-trunk

on:
  push:
    braches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

  Build-Android:
    needs: [Build]
    runs-on: ubuntu-latest
    container:
      image: 'docker://reactnativecommunity/react-native-android'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build Apk
        run: cd android && ./gradlew assembleDebug
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Android
          path: ./android/app/build/outputs
